### ISSUE TITLE
CRAN Warnings for version 0.4-12

### ISSUE THREAD

**Issue by idblr** [faosorios/fastmatrix#1]
Hi @faosorios, 

I noticed recent CRAN warnings for version 0.4-12. Do you expect to address these issues and resubmit to CRAN before the August 08, 2022 deadline?

https://cran.r-project.org/web/checks/check_results_fastmatrix.html

Cheers!
Ian

**Comment by faosorios** [comment]
Dear Ian,
I appreciate your message and reminder. All requested changes have been made but due to the fact that CRAN submissions are offline from Jul 22, 2022 to Aug 5, 2022 (see https://cran.r-project.org/), it will only be possible to send an update by that day. 
Warm regards,
Felipe

**Comment by idblr** [comment]
Thanks, Felipe! I'm sure the timing will work out under the CRAN circumstances. I appreciate your work on this package and SpatialPack

**Comment by idblr** [comment]
Hi Felipe, I see {fastmatrix} is back on CRAN. Congratulations. I see you also maintain {SpatialPack} and do you plan to resubmit it to CRAN, too? A package I maintain depends on {SpatialPack}.

**Comment by faosorios** [comment]
Dear Ian, I'm really sorry to inform you that the SpatialPack package was archived together with fastmatrix. Corrections will be made and a new version of SpatialPack will be resubmitted shortly.

**Comment by idblr** [comment]
Hi Felipe. That's OK! It's a good reason to update {gateR} anyway. Thanks for the work on {SpatialPack} and {fastmatrix}!

**Comment by faosorios** [comment]
Dear Ian, SpatialPack is once again available on CRAN. Thanks for your interest in SpatialPack and fastmatrix.

**Comment by idblr** [comment]
Thanks, Felipe!
